theme: jekyll-theme-minimal
name: Ali Ghandi Blog
logo: ./mypic.jpg
show_downloads: false
title: Data Land
description:  I am a Ph.D. student in Data Science and Data Scientist at Balad map company. Data Science enthusiastic.
